# Generated by Django 2.1.3 on 2018-12-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCat',
            new_name='SubCategory',
        ),
    ]
