# Generated by Django 2.1.3 on 2018-12-02 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('contacted_date', models.DateTimeField(blank=True, default=datetime.datetime)),
            ],
        ),
    ]
