# Generated by Django 2.1.3 on 2018-12-02 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('brand_Name', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('material_composition', models.CharField(blank=True, max_length=200)),
                ('return_days', models.CharField(blank=True, max_length=100)),
                ('warranty_days', models.CharField(blank=True, max_length=100)),
                ('is_male', models.BooleanField(blank=True, default=None)),
                ('is_female', models.BooleanField(blank=True, default=None)),
                ('is_child', models.BooleanField(blank=True, default=None)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('photo_main', models.CharField(max_length=200)),
                ('photo_1', models.CharField(blank=True, max_length=200)),
                ('photo_2', models.CharField(blank=True, max_length=200)),
                ('photo_3', models.CharField(blank=True, max_length=200)),
                ('photo_4', models.CharField(blank=True, max_length=200)),
                ('photo_5', models.CharField(blank=True, max_length=200)),
                ('photo_6', models.CharField(blank=True, max_length=200)),
                ('photo_7', models.CharField(blank=True, max_length=200)),
                ('photo_8', models.CharField(blank=True, max_length=200)),
                ('photo_9', models.CharField(blank=True, max_length=200)),
                ('photo_10', models.CharField(blank=True, max_length=200)),
                ('photo_11', models.CharField(blank=True, max_length=200)),
                ('photo_12', models.CharField(blank=True, max_length=200)),
                ('photo_13', models.CharField(blank=True, max_length=200)),
                ('photo_14', models.CharField(blank=True, max_length=200)),
                ('photo_15', models.CharField(blank=True, max_length=200)),
                ('size_1', models.CharField(blank=True, max_length=50)),
                ('size_2', models.CharField(blank=True, max_length=50)),
                ('size_3', models.CharField(blank=True, max_length=50)),
                ('size_4', models.CharField(blank=True, max_length=50)),
                ('size_5', models.CharField(blank=True, max_length=50)),
                ('size_6', models.CharField(blank=True, max_length=50)),
                ('size_7', models.CharField(blank=True, max_length=50)),
                ('size_8', models.CharField(blank=True, max_length=50)),
                ('size_9', models.CharField(blank=True, max_length=50)),
                ('size_0', models.CharField(blank=True, max_length=50)),
                ('size_11', models.CharField(blank=True, max_length=50)),
                ('size_12', models.CharField(blank=True, max_length=50)),
                ('size_13', models.CharField(blank=True, max_length=50)),
                ('size_14', models.CharField(blank=True, max_length=50)),
                ('size_15', models.CharField(blank=True, max_length=50)),
                ('color_1', models.CharField(blank=True, max_length=50)),
                ('color_photo1', models.CharField(blank=True, max_length=50)),
                ('color_2', models.CharField(blank=True, max_length=50)),
                ('color_photo2', models.CharField(blank=True, max_length=50)),
                ('color_3', models.CharField(blank=True, max_length=50)),
                ('color_photo3', models.CharField(blank=True, max_length=50)),
                ('color_4', models.CharField(blank=True, max_length=50)),
                ('color_photo4', models.CharField(blank=True, max_length=50)),
                ('color_5', models.CharField(blank=True, max_length=50)),
                ('color_photo5', models.CharField(blank=True, max_length=50)),
                ('listed_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subcategories.SubCat')),
            ],
        ),
    ]
